const QUESTIONS = [
  {
    type: "list",
    name: "ticker",
    message: "Select cryptocurrency:",
    choices: ["USDT", "BTC", "BNB", "BUSD", "ETH", "DAI"],
  },
  {
    type: "list",
    name: "fiat",
    message: "Select fiat currency:",
    choices: [
      "EUR",
      "USD",
      "AED",
      "AUD",
      "BDT",
      "BHD",
      "BOB",
      "BRL",
      "CAD",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CZK",
      "DOP",
      "DZD",
      "EGP",
      "GBP",
      "GEL",
      "GHS",
      "HKD",
      "IDR",
      "INR",
      "JPY",
      "KES",
      "KHR",
      "KRW",
      "KWD",
      "KZT",
      "LAK",
      "LBP",
      "LKR",
      "MAD",
      "MMK",
      "MXN",
      "MYR",
      "NGN",
      "OMR",
      "PAB",
      "PEN",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RUB",
      "SAR",
      "SDG",
      "SEK",
      "SGD",
      "THB",
      "TND",
      "TRY",
      "TWD",
      "UAH",
      "UGX",
      "UYU",
      "VES",
      "VND",
      "ZAR",
    ],
  },
  {
    type: "list",
    name: "operation",
    message: "Select exchange type:",
    choices: ["BUY", "SELL"],
  },
  {
    type: "list",
    name: "payTypes",
    message: "Select payment method:",
    choices: [{ name: "* (all)", value: null }, "AirTM", "Bank Transfer"],
  },
];

module.exports = QUESTIONS;
